### ISSUE TITLE
getting error in installing

### ISSUE THREAD

**Issue by rusrushal13** [dileepsankhla/QuickNotes#6]
```
rushal@rushal-GL552VW:~/Documents/github/QuickNotes/Key Logger$ make 
make: *** No rule to make target 'skeylogger.o', needed by 'skeylogger'.  Stop.
```
What do I need to do?

**Comment by dileepsankhla** [comment]
Hi @rusrushal13,
My bad, just change value `skeylogger.o` to `keylogger.o` in the `OBJS` macro.
In addition, change the `BIN_NAME` macro value to `keylogger`. (Not that necessary for now). 
Your updated `Makefile` will be like this : 
`CC := gcc
CFLAGS := -g -Wall
BIN_NAME := keylogger
OBJS := keylogger.o key_util.o options.o config.o

all: $(BIN_NAME)

$(BIN_NAME): $(OBJS)
	gcc $(CFLAGS) $(OBJS) -o $(BIN_NAME)

clean:
	rm -f *.o $(BIN_NAME)
`
P.S. Please go through the updated README.
